name = "Create Astral"
author = "Laskyyy"
version = "v2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "592de84c6b43582fb29a5c5bd8848d2a7665594abeaff3ea0778b42bc424249c"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
