[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 762726289341677668
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "In loading screen purgatory..."
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Create: Astral"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["curse"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "Modpage"
		url = "https://www.curseforge.com/minecraft/modpacks/create-astral"

	[[init.buttons]]
		label = "Discord"
		url = "https://discord.gg/StW3Q5K8dJ"


[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Pondering the menu buttons..."
	#The second line of text under the app name
	state = "Vibing to Astral Lakes..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Create: Astral"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["curse"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "Modpage"
		url = "https://www.curseforge.com/minecraft/modpacks/create-astral"

	[[main_menu.buttons]]
		label = "Discord"
		url = "https://discord.gg/StW3Q5K8dJ"


[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Pondering the menu buttons..."
	#The second line of text under the app name
	state = "Finding a server..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Create: Astral"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["curse"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "Modpage"
		url = "https://www.curseforge.com/minecraft/modpacks/create-astral"

	[[server_list.buttons]]
		label = "Discord"
		url = "https://discord.gg/StW3Q5K8dJ"


[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "Pondering the menu buttons..."
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Create: Astral"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["curse"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "Modpage"
		url = "https://www.curseforge.com/minecraft/modpacks/create-astral"

	[[realms_list.buttons]]
		label = "Discord"
		url = "https://discord.gg/StW3Q5K8dJ"


[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Stuck in purgatory,"
	#The second line of text under the app name
	state = "Joining a game..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Create: Astral"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["curse"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "Modpage"
		url = "https://www.curseforge.com/minecraft/modpacks/create-astral"

	[[join_game.buttons]]
		label = "Discord"
		url = "https://discord.gg/StW3Q5K8dJ"


[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently In %world%"
	#The second line of text under the app name
	state = "Being Productive (Singleplayer)"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Create: Astral"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["curse"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "Modpage"
		url = "https://www.curseforge.com/minecraft/modpacks/create-astral"

	[[single_player.buttons]]
		label = "Discord"
		url = "https://discord.gg/StW3Q5K8dJ"


[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %servername% with %players% players"
	#The second line of text under the app name
	state = "Making Friends (Multiplayer)"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Create: Astral"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["curse"]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "Modpage"
		url = "https://www.curseforge.com/minecraft/modpacks/create-astral"

	[[multi_player.buttons]]
		label = "Discord"
		url = "https://discord.gg/StW3Q5K8dJ"


[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 
	buttons = []

[generic]
	#The first line of text under the app name
	description = "Playing Create: Astral"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["https://media.forgecdn.net/avatars/768/269/638104922297531668.png"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = ""
		url = ""

	[[generic.buttons]]
		label = ""
		url = ""


[custom]
	#Must these variables be parsed along with other variables
	enabled = false
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = ["overworld"]
		largeImageText = "In the Overworld"
		smallImageKey = ["mclogo"]
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = ["nether"]
		largeImageText = "In the Nether"
		smallImageKey = ["mclogo"]
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = ["end"]
		largeImageText = "In the End"
		smallImageKey = ["mclogo"]
		smallImageText = "%mods% mods installed"
		buttons = []


