logMissingOptional = false
logFirstEitherError = false
boxRenderTime = 10000
structureRenderTime = 10000
blockTagCycleTime = 1000
itemSlotCycleTime = 1000
needAdvancedInfoForRecipeID = true
modelFolders = ["machine", "machines"]
